export const ADD_LOCATION = 'ADD_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const DESELECT_LOCATION = 'DESELECT_LOCATION';

export const SET_LOCATIONS = 'SET_LOCATIONS';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";